#!/bin/bash

func_usage() {
(echo "Usage:
exporter.sh -h | exporter.sh --help
  prints this help and exits
exporter.sh INPUT 
  INPUT is a valid deck file (.txt generated by anki)")
}


# Checks if there is only one arg and if the help is desired or not
if [ "$#" -ne 1 ] || [ "X$1" = "X-h" ] || [ "X$1" = "X--help" ]
then
		func_usage
else
		FILE=$(basename "$1" .txt)
		DIR="${FILE}-export/"

		# delete last generated output
		rm -rf ${DIR}

		# genrate tex file
		java -jar .txt-to-tex-exporter.jar ./test.txt ${DIR}

		cd ${DIR}
		./../.tex-to-pdf-exporter.sh $FILE.tex >/dev/null 
fi

