#!/bin/bash

func_usage() {
(echo "Usage:
exporter.sh -h | exporter.sh --help
  prints this help and exits
exporter.sh INPUT 
  INPUT is a valid deck file (.txt generated by anki)")
}


# Checks if there is only one arg and if the help is desired or not
if [ "$#" -ne 1 ] || [ "X$1" = "X-h" ] || [ "X$1" = "X--help" ]
then
		func_usage
else
		# generate the fully qualified input path
		FQ_INPUT="$(realpath $1)"

		# remove extension, but keep fully qualified input path
		FQ_FILE=$(basename ${FQ_INPUT} .txt)

		# generate output directory
		OUTPUT_DIR="${FQ_FILE}-export/"

		# get the script directory
		SCRIPT_DIR="$(dirname $0)"

		# delete last generated output
		# rm -rf ${OUTPUT_DIR}

		# genrate tex file
		java -jar $SCRIPT_DIR/.txt-to-tex-exporter.jar ${FQ_INPUT} ${OUTPUT_DIR} path/to/img/

		cd ${OUTPUT_DIR}
		./../.tex-to-pdf-exporter.sh $FQ_FILE.tex >/dev/null 
fi

